### ISSUE TITLE
哇，想不到有人也在做类似的工作

### ISSUE THREAD

**Issue by SnowingFox** [Mini-ghost/vue-composition-form#1]
我也在做一个类似的库，不过我是按照react-hook-form路线走的

https://github.com/vue-use-form/vue-use-form

欢迎star

**Comment by SnowingFox** [comment]
抱歉，我不知道我这样做是不是违反了开源社区的规定，我先close掉这个issue吧，打扰了

**Comment by Mini-ghost** [comment]
@SnowingFox 
嗨！我看過你開發的 vue-use-form 了，很期待完成後的成果。

Vue Composition Form 也深受 React Hook Form、Formik 與 VeeValidate 影響，我大量參考了他們的 API 設計與解決問題的方法，在邊研究邊開發的過程學習到了很多，也被他們所顧慮到的細節深深的驚豔，我相信你也會有相同的感受。

我真的蠻意外會這麼快收到 issue，雖然這不是一個真正的問題回報，但還是很感謝你分享想你的開源專案。之後如果有這方面的技術想要討論，非常歡迎透過 Twitter 或是在我的個人網站中有其他聯絡方式可以找到我，謝謝 💚
